language: node_js
node_js:
  - "13.5"
install:
  - npm install
script:
  - npm run build:static
deploy:
  # deploy next.seven23.io on github page
  - provider: pages
    skip_cleanup: true
    local_dir: dist/browser
    fqdn: https://sebastienbarbier.com
    github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    on:
      branch: master
